apiVersion: apps/v1
kind: Deployment

metadata:
  name: aks-observability-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: aks-observability-app

  template:
    metadata:
      labels:
        app: aks-observability-app

    spec:
      containers:
      - name: aks-observability-app

        image: sowndaracr001.azurecr.io/aks-observability:77e8884847f7155951d077d38b3f80c9c3ce6423

        ports:
        - containerPort: 5000

